apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      name: auth
  template:
    metadata:
      labels:
        name: auth

    spec:
      containers:
        - name: auth
          image: vishaldocker012/auth1
          env:
            - name: MONGO_URI
              value: mongodb://auth-mongodb-clusterip-srv:27017/auth
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-srv

spec:
  selector:
    name: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
