apiVersion : apps/v1
kind : Deployment
metadata : 
 name : next-depl

spec : 
 replicas : 1
 selector :
  matchLabels :
    app : nextjs
 template :
   metadata : 
    labels : 
      app : nextjs
   spec : 
    containers : 
     - name : nextjs
       image : vishaldocker012/nextjs

---
apiVersion : v1 
kind : Service 
metadata :
 name : nextjs-clusterip-srv

spec :
 selector :
  app : nextjs
 ports : 
  - name : nextjs-srv
    protocol : TCP
    port : 3000
    targetPort : 3000
  